### ISSUE TITLE
How to extract .aa files & How to split the file for each patient

### ISSUE THREAD

**Issue by Praveengovianalytics** [iiscleap/Coswara-Data#10]
Hi  Team,

I am facing issue in using the .aa files in each date dataset , Need your assistance in extract the data 

Question 1 :- How we can extract the .aa files , Is there any python Code snippet or library exist 

Question 2 :- 
I have came across "from pydub import AudioSegment" library , What is the params for each patient
frame_rate
channels
sample_width

Each .aa files definitely contains samples of multiple patient / day 

Thanks

**Comment by prash29** [comment]
Hi,

1) There is a script `extract_data.py` in the repo which will extract the data from all the zipped files folder-wise. 

2) In our scripts, we have used the Librosa package, as an alternative to Pydub. Most files in our repo are of sampling rate 44100 Hz and all files are single channel. I'm adding a code snippet below on loading files using librosa

`sampling_rate = 44100`
`s,_ = librosa.load(file_path,sr=sampling_rate)`
