### ISSUE TITLE
Problems with covid_status column

### ISSUE THREAD

**Issue by gandrey77** [iiscleap/Coswara-Data#11]
I'm having some problems to understand the meaning of the labels in covid_satus column.

What does mean "resp_illness_not_identified" and "no_resp_illness_exposed"?  

"resp_illness_not_identified" = the person does not have respiratory problems? or the person has respiratory problems but dont know what illness he has?
"no_resp_illness_exposed" = the person does not have respiratory problems but he was exposed to corona virus?

**Comment by prash29** [comment]
Hi,

"resp_illness_not_identified" implies that the person chose an option saying he has pre-existing respiratory illnesses but he's not been identified with COVID-19.

"no_resp_illness_exposed" implies that the person chose the option saying he does not have any respiratory illnesses but he could be exposed to COVID through contact.

**Comment by gandrey77** [comment]
ahh ok.Tks for the explanation. Regards
