### ISSUE TITLE
unable to extract  in windows 

### ISSUE THREAD

**Issue by Rakesh2109** [iiscleap/Coswara-Data#12]
The archive is corrupt

**Comment by prash29** [comment]
Hi,

All the tarred files are okay. They aren't corrupt. If you're using Windows Powershell or Ubuntu bash on Windows, the current code should work. If you are using the Windows Command Prompt, then in Line 28 of `extract_data.py` change the word `cat` to `type`. This should solve the issue (assuming you have tar installed)

We will try adding compatibility with different kinds of OS in the `extract_data.py` script itself soon. 

Thanks
