### ISSUE TITLE
Missing id numbers in the outcome variable file

### ISSUE THREAD

**Issue by mikepett92** [iiscleap/Coswara-Data#2]
Thank you for this great dataset. Will the ids for the most recent set of participants (pushed 07/07) be paired with the provided recordings? The ids are currently missing from the .csv file. Thank you!

**Comment by drewgrant** [comment]
Hello! Thanks for the dataset! I have been having quite a bit of trouble extracting the tar files unless they have the ".aa" extension. The other tar files (e.g. ".ab", ".ac", ".ad", etc.) give my tar extractors error messages suggesting the tar files are not archives and are in an unrecognized format. Could someone please help me figure out how to resolve this issue?
