### ISSUE TITLE
Unable to Open

### ISSUE THREAD

**Issue by digs1998** [iiscleap/Coswara-Data#4]
I am not able to access the tar files, as they are in patterns of aa, ab and so on

**Comment by prash29** [comment]
Hi, 

Sorry for the late response. In the last part of the README, there are a few lines about how you can extract these tar files. 

If the folder name is `20200814`, then you will run `cat *.tar.gz.* > file_name.tar.gz` inside the  `20200814` folder followed by `tar -xvzf file_name.tar.gz` .

Thank you for your query. I will look into adding a script in the repo that will perform the extraction of the folders.

**Comment by prash29** [comment]
A script `extract_data.py` has been added to the repository. This will extract all the wav files in date-wise directories.
