### ISSUE TITLE
The full name of label in CSV file

### ISSUE THREAD

**Issue by DongqiShen** [iiscleap/Coswara-Data#5]
Actually, I  cannot find the full name of labels in CSV file, such as ep, rU, ht, um, ihd and etc, though some labels are obviously.
Could you please upload a file like a map, a -- age, g--gender. Thank you.

**Comment by talhakabakus** [comment]
Agree with @DongqiShen, could you please share the descriptions of those abbreviations? @prash29 @iiscleap

**Comment by prash29** [comment]
Hi,

Sorry for the late reply. Yes, I will update a map for the labels in the CSV on this repo soon. Thank you for your interest in the work.

**Comment by talhakabakus** [comment]
No problem @prash29, many thanks for all your hard work and thanks in advance for your care.
All the best.

**Comment by prash29** [comment]
Hi,
I've added a file named `csv_labels_legend.json` in the repository which is a json that contains information about all the labels in `combined_data.csv`

**Comment by talhakabakus** [comment]
That's what exactly needed. Thank you very much for your care, @prash29.

**Comment by prash29** [comment]
Glad this helped. Thanks @talhakabakus !
