### ISSUE TITLE
Paper mentioned there are 3470 clean audios, but the sample count from README add up to less than 1500 samples

### ISSUE THREAD

**Issue by sirgarfieldc** [iiscleap/Coswara-Data#6]
Same as title. Any clarification ? 

Paper link: https://arxiv.org/abs/2005.10548

**Comment by prash29** [comment]
Hi,

Thanks for your query. The README describes the number of users uploaded for that particular date stamp. For each user, we record 9 sound categories. The current number of total samples is more than what is described in the Arxiv paper, as that was written some time back. 

Note: The number of users updated in the README is the complete raw data of users who have completed all categories. They aren't annotated as clean or noisy audio.

**Comment by sirgarfieldc** [comment]
Thank you for the response. I am currently writing a review paper relating to the application of computational audition on Covid19.  

Do you have the most up-to-date numbers for the following ? 

1. number of clean , usable and labelled recordings
2. proportion of unhealthy subjects ( infected / cured / exposed)

**Comment by prash29** [comment]
Hi,

You can obtain the statistics of the different categories of the subjects from `combined_data.csv`. 

For the proportion of clean/noisy recordings, as it is a crowdsourced dataset, we currently don't have the details about that for the entire dataset. We do have that data for a subset of the dataset at https://github.com/iiscleap/Coswara-Exp if it helps.

**Comment by aadnesd** [comment]
> Thank you for the response. I am currently writing a review paper relating to the application of computational audition on Covid19.
> 
> Do you have the most up-to-date numbers for the following ?
> 
> 1. number of clean , usable and labelled recordings
> 2. proportion of unhealthy subjects ( infected / cured / exposed)

Hi @prash29, this review paper seems interesting to my thesis. Have you published it?
