### ISSUE TITLE
Issue regarding extracting the dataset

### ISSUE THREAD

**Issue by azamk64** [iiscleap/Coswara-Data#7]
I have run the extract_data.py file but it could download the wav file , it just create a empty folder  called extracted data , kindly help me out thanks

**Comment by prash29** [comment]
If you have downloaded the entire repo and then run the `extract_data.py` script, I don't see what could have gone wrong. I have cross-checked the code as well and it works. Can you try cloning the entire repository again and then check?

**Comment by azamk64** [comment]
Sure

**Comment by azamk64** [comment]
Kindly do tell me what {
 coswara_data_dir = os.path.abspath('.') # Local Path of iiscleap/Coswara-Data Repo}
should be there is os.path.abspath parameter to extract the wav file i have tried but it gives cat internal or external command error

**Comment by prash29** [comment]
I think this might be an issue with the Windows terminal not having the cat command that is being used in the `extract_data.py` script. I think it should work with Windows Powershell. You can also look into Windows subsystem for Linux (WSL).
