### ISSUE TITLE
I do not open files named tar.gz.ab-ac-ad..aj, but the file named tar.gz.aa can be opened. There is no problem with the files named aa. How can I solve this problem?

### ISSUE THREAD

**Issue by beyzant** [iiscleap/Coswara-Data#8]
The terminal error is as follows;
tar: Error opening archive: Unrecognized archive format
When I investigated the terminal error, I could not reach the results to solve the error. I am a macOS user. How can I solve this problem? 
I would be very grateful if you could help.

**Comment by prash29** [comment]
Hi, If you clone the updated version of this repo. I have added a script called `extract_data.py`. The script will extract all the wav files from all the directories. Hope this helps!

**Comment by beyzant** [comment]
Thank you for the answer i will try as soon as possible

**Comment by beyzant** [comment]
thank you I coloned and was able to open with python code
