### ISSUE TITLE
Extracting data windows

### ISSUE THREAD

**Issue by aadnesd** [iiscleap/Coswara-Data#9]
When I try to run the extract data script on windows I get a message saying <'cat' is not recognized as an internal or external command> and no data is extracted. Do you have a workaround?

**Comment by prash29** [comment]
Hi,

You can try running this using the Windows Subsystem for Linux (WSL) on Windows 10.
But, I also guess there's a command equivalent to 'cat' in Windows called 'type'. Maybe you can try replacing the line in the code which uses the command 'cat' to 'type' and check if that works.

**Comment by aadnesd** [comment]
Hi, replacing the 'cat' command with 'type' gives:
"The syntax of the command is incorrect.
tar: Error opening archive: Failed to open '\\.\tape0'"

**Comment by prash29** [comment]
I think this might be an issue with the Windows terminal not having compatibility with tar. I think it should work with Windows Powershell. You can also look into Windows subsystem for Linux (WSL).
